### ISSUE TITLE
Remove OS option

### ISSUE THREAD

**Issue by ishantanu** [kubernauts/tk8-provisioner-cattle-aws#6]
At this point, using `os` option doesn't really make much sense since it is much simpler for the user to specify AMI ID instead of OS and then let tk8 select the specific AMI ID.

Using only AMI ID also simplifies the requirements from user's point of view.

**Comment by arashkaffamanesh** [comment]
100%

**Comment by ishantanu** [comment]
Reopened. This requires more changes.
